# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a996adfb454dcc3d13dc948c9c1584712391950d560862775265a76614de57b1758c0345d354a592dbe00586fb537a09a3ad1ae37aa993827d86779025c6238

test:
  secret_key_base: b36f619f3952bf7382f80a7b23ca4e306e0f718df4a728759780f418ad8154e44dcf9e357a47057e065d14442a3addd35f88fec11d55cf1a1ac042fa8c42abd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
